### ISSUE TITLE
cargo hackerman explain to have an option to save .xdot file

### ISSUE THREAD

**Issue by peter-lyons-kehl** [pacak/hackerman#7]
Hi Michael or friend. Thank you for hackerman.

Unfortunately, XDot (the standard viewer on Manjaro Linux with GNOME) doesn't offer a way to save the .xdto file (only to print it to an SVG or PDF). Could you add an option to save the file (and/or not to remove it after XDot is finished, as you see most robust), please?

**Comment by pacak** [comment]
I usually take a screenshot to store bits I care about. What are you going to do with `.xdot` file once you have it?
